version: '3.4'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  knightschallenge:
    image: ${DOCKER_REGISTRY-}knightschallenge
    build:
      context: ./KnightsChallenge
      dockerfile: Dockerfile
    container_name: api
    environment:
      - MongoDBSettings__ConnectionString=mongodb://mongodb:27017
    depends_on:
       - mongodb
    ports:
       - 8080:8080

  frontend:
    build:
      context: ./knightschallengefront
      dockerfile: Dockerfile
    container_name: front
    ports:
      - "3000:3000"
    depends_on:
      - knightschallenge



volumes:
  mongo-data:
